stages:
  - build
  - release

build-docker:
  stage: build
  image: # using more verbose form of 'image' so entrypoint can be overridden.
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""] # script won't start without overriding this - it jumps straight to kaniko
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  tags:
    - "localtest"

release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: [""]
  only:
    - tags
    - main
  variables:
    GIT_DEPTH: 0
  script:
    - goreleaser release --clean --snapshot
  artifacts:
    paths:
      - "dist/*"
    expire_in: 1 week
  tags:
    - "localtest"
