stages:
  - release

release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: [""]
  only:
    - tags
    - main
  variables:
    GIT_DEPTH: 0
  script:
    - goreleaser release --clean
