# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
gitlab_urls:
  use_package_registry: true
release:
  ids:
    - logwild_tar
archives:
  - format: tar.gz
    id: logwild_tar
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - config/**
      - README.md
      - LICENSE
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - repository:
      owner: alertinnovation/devops
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_RELEASE_TOKEN }}"
    homepage: "https://gitlab.com/alertinnovation/devops/tools/sconn" # this doesn't actually exist !
    url_template: https://gitlab.com/api/v4/projects/{{ .Env.CI_PROJECT_ID }}/packages/generic/sconn/{{ trimprefix .Tag "v"}}/{{ .ArtifactName }}
    folder: Formula
    install: |-
      bin.install "sconn"
      share.install Dir["config/*"]
    test: |-
      system "#{bin}/sconn install"
    download_strategy: GitlabPrivateRepositoryReleaseDownloadStrategy
    custom_require: lib/private_strategy
    dependencies:
      - name: fzf
      - name: azure-cli
# chocolateys:
#   - source_repo: "https://alertinnovation.jfrog.io/artifactory/api/nuget/devops-nuget/"
#     api_key: '{{ .Env.CI_REGISTRY_PASSWORD }}'
#     project_url: "https://gitlab.com/alertinnovation/devops/tools/sconn" # this doesn't actually exist !
#     url_template: https://gitlab.com/api/v4/projects/{{ .Env.CI_PROJECT_ID }}/packages/generic/sconn/{{ trimprefix .Tag "v"}}/{{ .ArtifactName }}
#     dependencies:
#     - id: fzf
#     - id: azure-cli
# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

